name: Deploy

on:
  push:
    branches:
      - master

jobs:
  storefronter_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        timeout-minutes: 10
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          buildpack: "https://github.com/heroku/heroku-buildpack-nodejs.git"
          dontautocreate: true # Set this to true if you don't want to automatically create the Heroku app
